buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: CMSAssetBuildpack
  branch: master

before:
  - description: Copies assets in the src directory to an @hubspot/sprout directory
    commands:
      - mkdir -p @hubspot/sprout
      - cp -rv src/* @hubspot/sprout
