buildDeps:
  - hs-build-tools
  - node-8.9.3

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: CMSAssetBuildpack
  branch: master

before:
  - description: Lint the files
    commands:
      - prod-lint

  - description: Copies assets in the src directory to an @hubspot/sprout directory
    commands:
      - mkdir -p @hubspot/sprout
      - cp -rv src/* @hubspot/sprout
