buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: CMSAssetBuildpack
  branch: master

before:
  - description: Copies assets in the src directory to an @hubspot/sprout directory
    commands:
      - mkdir -p @hubspot/sprout
      - cp .major_version @hubspot/
      - cp .asset_gate @hubspot/
      - cp -rv src/. @hubspot/sprout
